[package]
name = "lessink"
version = "0.1.0"
edition = "2024"

[dependencies]
pest = "2.8.0"
pest_derive = "2.8.0"
once_cell = "1.21.3"
walkdir = "2"
clap = { version = "4.5.35", features = ["derive", "wrap_help"]}
